test: test ci/cd

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -47,4 +47,12 @@ jobs:
         run: sleep 10
 
       - name: Restart the application
-        run: nohup java -jar /home/ec2-user/downloads/server-1.jar > /home/ec2-user/downloads/output.log 2> /home/ec2-user/downloads/errors.log &
+        run: |
+          nohup java -jar /home/ec2-user/downloads/server-1.jar > /home/ec2-user/downloads/output.log 2> /home/ec2-user/downloads/errors.log &
+          APP_PID=$!
+          echo "Application PID: $APP_PID"
+          sleep 10
+          if ! pgrep -f 'java -jar /home/ec2-user/downloads/server-1.jar' > /dev/null; then
+            echo "Application failed to start"
+            exit 1
+          fi
